import { Scale, CheckCircle2, AlertTriangle, FileText } from 'lucide-react';

export default function TermsPage() {
  return (
    <div className="container mx-auto px-4 md:px-6 py-12 max-w-4xl space-y-8">
      <div className="border-b border-slate-800 pb-6">
        <h1 className="text-3xl font-bold text-white tracking-tight">Terms and Conditions</h1>
        <p className="text-sm text-slate-400 mt-2">
          Terms of Service & Regulatory Framework for Saans Air Safety School Planner.
        </p>
      </div>

      <div className="space-y-6 text-sm text-slate-300 leading-relaxed">
        <section className="space-y-2">
          <h2 className="text-lg font-bold text-white flex items-center gap-2">
            <Scale className="w-5 h-5 text-sky-400" />
            1. Acceptance of Operational Terms
          </h2>
          <p>
            By accessing or operating the Saans automated planner, educational institutions, administrators, and participating users agree to abide by these terms and the Commission for Air Quality Management (CAQM) Graded Response Action Plan directives.
          </p>
        </section>

        <section className="space-y-2">
          <h2 className="text-lg font-bold text-white flex items-center gap-2">
            <CheckCircle2 className="w-5 h-5 text-emerald-400" />
            2. Deterministic Schedule Re-planning
          </h2>
          <p>
            Schedule modifications generated by the deterministic engine under declared GRAP Stages I, II, III, and IV are designed to preserve physical education curriculum requirements while eliminating high-exposure outdoor activities. Final execution rests with school leadership.
          </p>
        </section>

        <section className="space-y-2">
          <h2 className="text-lg font-bold text-white flex items-center gap-2">
            <AlertTriangle className="w-5 h-5 text-amber-400" />
            3. Verification & SHA-256 Proof Receipts
          </h2>
          <p>
            Cryptographic receipts generated upon plan approval represent immutable proof of regulatory compliance. Tampering with local verification state triggers browser-level cryptographic integrity alerts.
          </p>
        </section>

        <section className="space-y-2">
          <h2 className="text-lg font-bold text-white flex items-center gap-2">
            <FileText className="w-5 h-5 text-indigo-400" />
            4. Limitation of Liability
          </h2>
          <p>
            Environmental air quality forecasts are sourced from CAAQMS monitoring networks. Saans provides real-time optimization tools and advisory notifications to mitigate student health risks.
          </p>
        </section>
      </div>
    </div>
  );
}
